Pantheios - The C++ Diagnostic Logging Sweetspot
Pantheios Util API
Contains utility functions used by the group__core_library and by application programs using Pantheios.
Functions
pan_char_t const * pantheios_getStockSeverityString (pan_sev_t severity)
Returns a constant pointer to a non-NULL non-modifiable nul-terminated string representing the severity level.
size_t pantheios_getStockSeverityStringLength (pan_sev_t severity)
Returns the length of the string returned by pantheios_getSeverityString().
char const * pantheios_getInitCodeString (int code)
Returns a constant pointer to a non-NULL non-modifiable nul-terminated string representing the initialisation code.
size_t pantheios_getInitCodeStringLength (int code)
Returns the length of the string returned by pantheios_getInitCodeString().
Detailed Description
Contains utility functions used by the group__core_library and by application programs using Pantheios.
Function Documentation
char const* pantheios::pantheios_getInitCodeString (int code)
Returns a constant pointer to a non-NULL non-modifiable nul-terminated string representing the initialisation code.
Parameters:
code The initialisation code whose string explanation is to be returned. If the error code is not recognised, the empty string ("") will be returned.
Referenced by pantheios::getInitCodeString().
size_t pantheios::pantheios_getInitCodeStringLength (int code)
Returns the length of the string returned by pantheios_getInitCodeString().
Parameters:
code The initialisation code whose string equivalent is to be returned. If the error code is not recognised, 0 will be returned.
Referenced by pantheios::getInitCodeStringLength().
pan_char_t const* pantheios::pantheios_getStockSeverityString (pan_sev_t severity)
Returns a constant pointer to a non-NULL non-modifiable nul-terminated string representing the severity level.
Parameters:
severity The severity level whose string equivalent is to be returned. Must be one of the PANTHEIOS_SEV_* enumerators, otherwise, the empty string ("") will be returned.
Referenced by pantheios::getStockSeverityString().
size_t pantheios::pantheios_getStockSeverityStringLength (pan_sev_t severity)
Returns the length of the string returned by pantheios_getSeverityString().
Parameters:
severity The severity level whose string equivalent is to be returned. Must be one of the PANTHEIOS_SEV_* enumerators, otherwise, 0 will be returned.
Referenced by pantheios::getStockSeverityStringLength().
pantheios Library documentation © Matthew Wilson & Synesis Software, 2006-2015